# Generated by Django 2.1.5 on 2021-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/cart_image_placeholder.png', null=True, upload_to=''),
        ),
    ]
