# Generated by Django 2.1.5 on 2021-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210118_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='cart_image_placeholder.png', null=True, upload_to=''),
        ),
    ]
